- hosts: all
  gather_facts: false
  roles:
    - windows-docker-role
  tasks:

    - name: Docker role
      import_role:
        name: windows-docker-role
      when: install_docker

    - name: Ping test
      jimbo8098.win_docker_collection.win_ping_test:

    - name: Test module
      jimbo8098.win_docker_collection.docker_swarm:
        advertise_addr: '{{ advertise_addr }}'
        listen_addr: '{{ listen_addr }}'
